# “At minute 25 past hour 0, 2, 4, 8, and 12.”
on:
  schedule:
    - cron: "25 0,2,4,8,12 * * *"
name: Build Gatsby Site
jobs:
  build:
    name: Build Gatsby Site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Gatsby Site
      uses: jzweifel/gatsby-cli-github-action@master
      with:
        gatsby-arg: build